### PR TITLE
Fix typo in print_globals

### PR DESCRIPTION
**Pull request by jonas-hag**
In `print_globals`, there is a small typo. I changed "Fonctions" to "Functions"

### CODE REVIEW

**Comment by jonas-hag** [comment]
Sorry for my oversight with the test and thanks for fixing it!

**Comment by statnmap** [comment]
No worries. Thank you for your contribution.

**Comment by statnmap** [comment]
Note that your commit email is not the linked to your GitHub account. You appear to be 2 different persons :smiley:

**Comment by jonas-hag** [comment]
> Note that your commit email is not the linked to your GitHub account. You appear to be 2 different persons 😃

yeah, I'm currently struggling to manage two accounts from the same machine with RStudio and haven't found a good solution yet

**Pull request merged**
